// import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/Components/common/NavBar/NavBar";
import image from '@/asstes/images/raaya_logo.png'
import Head from "next/head";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

interface IconConfig {
  icon: string;
}

interface Metadata {
  title: string;
  icons: IconConfig;
  description?: string;
}

export const metadata: Metadata = {
  title: "Raaya Social",
  icons: {
    icon: image.src
  }
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
      </Head>
      <body
        className={`poppins-regular container`}
      >
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
